"""empty message

Revision ID: 266c49ad27cf
Revises: 1ddaa69807ad
Create Date: 2021-11-18 12:58:58.898153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '266c49ad27cf'
down_revision = '1ddaa69807ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tweet_created_at'), 'tweet', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tweet_created_at'), table_name='tweet')
    op.drop_table('tweet')
    # ### end Alembic commands ###
